import { db } from '@/db/db';

import { daily_entries, goals, tasks } from './schema';

export async function seedDummyData() {
  // Insert 20 diverse goals
  const insertedGoals = await db.insert(goals).values([
    {
      title: 'Complete AppliGO MVP',
      description: 'Finish the minimal viable product by May 1st, 2025',
      created_at: '2025-04-10T10:00:00Z',
    },
    {
      title: 'Learn Drizzle ORM',
      description: 'Master Drizzle ORM and SQLite integration',
      created_at: '2025-04-05T15:30:00Z',
    },
    {
      title: 'Build Personal Portfolio Website',
      description: 'Create a modern, responsive portfolio showcasing my projects and skills',
      created_at: '2025-03-15T09:00:00Z',
    },
    {
      title: 'Master React Server Components',
      description: 'Deep dive into RSC architecture and best practices',
      created_at: '2025-03-20T14:30:00Z',
    },
    {
      title: 'Launch SaaS Side Project',
      description: 'Build and deploy a productivity tool for small teams',
      created_at: '2025-02-28T11:15:00Z',
    },
    {
      title: 'Get AWS Solutions Architect Certification',
      description: 'Study and pass the AWS SAA-C03 exam',
      created_at: '2025-03-01T08:45:00Z',
    },
    {
      title: 'Improve Code Review Skills',
      description: 'Become more effective at giving and receiving code reviews',
      created_at: '2025-04-01T16:20:00Z',
    },
    {
      title: 'Build Mobile App with React Native',
      description: 'Create a cross-platform mobile application',
      created_at: '2025-01-15T13:30:00Z',
    },
    {
      title: 'Learn System Design Patterns',
      description: 'Study scalable architecture patterns and distributed systems',
      created_at: '2025-02-10T10:45:00Z',
    },
    {
      title: 'Contribute to Open Source Project',
      description: 'Make meaningful contributions to a popular OSS project',
      created_at: '2025-03-25T15:00:00Z',
    },
    {
      title: 'Master GraphQL and Apollo',
      description: 'Learn GraphQL federation and advanced Apollo features',
      created_at: '2025-04-15T12:30:00Z',
    },
    {
      title: 'Build CI/CD Pipeline',
      description: 'Set up automated testing and deployment workflows',
      created_at: '2025-03-10T09:15:00Z',
    },
    {
      title: 'Learn Docker and Kubernetes',
      description: 'Master containerization and orchestration technologies',
      created_at: '2025-02-20T14:00:00Z',
    },
    {
      title: 'Improve Database Performance',
      description: 'Learn query optimization and database indexing strategies',
      created_at: '2025-04-20T11:45:00Z',
    },
    {
      title: 'Build Real-time Chat Application',
      description: 'Create a WebSocket-based chat app with message persistence',
      created_at: '2025-01-30T16:30:00Z',
    },
    {
      title: 'Learn TypeScript Advanced Features',
      description: 'Master utility types, conditional types, and advanced TS patterns',
      created_at: '2025-03-05T10:20:00Z',
    },
    {
      title: 'Implement Authentication System',
      description: 'Build secure auth with JWT, OAuth, and role-based access control',
      created_at: '2025-04-25T13:15:00Z',
    },
    {
      title: 'Optimize Web Performance',
      description: 'Learn Core Web Vitals optimization and performance monitoring',
      created_at: '2025-02-15T15:45:00Z',
    },
    {
      title: 'Build E-commerce Platform',
      description: 'Create a full-featured online store with payment integration',
      created_at: '2025-01-20T08:30:00Z',
    },
    {
      title: 'Master Testing Strategies',
      description: 'Learn unit, integration, and e2e testing best practices',
      created_at: '2025-03-30T17:00:00Z',
    },
  ]);

  // Generate goal IDs (assuming auto-increment starting from 1)
  const goalIds = Array.from({ length: 20 }, (_, i) => i + 1);

  // Insert 80+ tasks across all goals
  await db.insert(tasks).values([
    // Tasks for Goal 1: Complete AppliGO MVP
    {
      goal_id: goalIds[0],
      title: 'Setup database schema',
      is_done: 1,
      energy_level: 'high',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[0],
      title: 'Build UI components',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[0],
      title: 'Implement user authentication',
      is_done: 1,
      energy_level: 'high',
      time_estimate: 240,
    },
    {
      goal_id: goalIds[0],
      title: 'Create API endpoints',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 200,
    },
    {
      goal_id: goalIds[0],
      title: 'Add data validation',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[0],
      title: 'Setup deployment pipeline',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 150,
    },

    // Tasks for Goal 2: Learn Drizzle ORM
    {
      goal_id: goalIds[1],
      title: 'Read Drizzle docs',
      is_done: 1,
      energy_level: 'low',
      time_estimate: 60,
    },
    {
      goal_id: goalIds[1],
      title: 'Practice basic queries',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[1],
      title: 'Learn migration system',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[1],
      title: 'Build sample project',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 180,
    },

    // Tasks for Goal 3: Build Personal Portfolio Website
    {
      goal_id: goalIds[2],
      title: 'Design wireframes',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[2],
      title: 'Setup Next.js project',
      is_done: 1,
      energy_level: 'low',
      time_estimate: 30,
    },
    {
      goal_id: goalIds[2],
      title: 'Create landing page',
      is_done: 1,
      energy_level: 'high',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[2],
      title: 'Build projects showcase',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 240,
    },
    {
      goal_id: goalIds[2],
      title: 'Add contact form',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[2],
      title: 'Optimize for SEO',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 120,
    },

    // Tasks for Goal 4: Master React Server Components
    {
      goal_id: goalIds[3],
      title: 'Study RSC fundamentals',
      is_done: 1,
      energy_level: 'low',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[3],
      title: 'Practice data fetching patterns',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 150,
    },
    {
      goal_id: goalIds[3],
      title: 'Build demo application',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 300,
    },
    {
      goal_id: goalIds[3],
      title: 'Learn streaming and suspense',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 180,
    },

    // Tasks for Goal 5: Launch SaaS Side Project
    {
      goal_id: goalIds[4],
      title: 'Market research',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 240,
    },
    {
      goal_id: goalIds[4],
      title: 'Define MVP features',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[4],
      title: 'Setup project structure',
      is_done: 1,
      energy_level: 'high',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[4],
      title: 'Build core features',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 480,
    },
    {
      goal_id: goalIds[4],
      title: 'Integrate payment system',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 200,
    },
    {
      goal_id: goalIds[4],
      title: 'Create landing page',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 180,
    },

    // Tasks for Goal 6: AWS Solutions Architect Certification
    {
      goal_id: goalIds[5],
      title: 'Buy study materials',
      is_done: 1,
      energy_level: 'low',
      time_estimate: 30,
    },
    {
      goal_id: goalIds[5],
      title: 'Study compute services',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[5],
      title: 'Study storage services',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 150,
    },
    {
      goal_id: goalIds[5],
      title: 'Practice labs',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 240,
    },
    {
      goal_id: goalIds[5],
      title: 'Take practice exams',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[5],
      title: 'Schedule real exam',
      is_done: 0,
      energy_level: 'low',
      time_estimate: 15,
    },

    // Tasks for Goal 7: Improve Code Review Skills
    {
      goal_id: goalIds[6],
      title: 'Read code review best practices',
      is_done: 1,
      energy_level: 'low',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[6],
      title: 'Practice giving constructive feedback',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 60,
    },
    {
      goal_id: goalIds[6],
      title: 'Learn automated review tools',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 120,
    },

    // Tasks for Goal 8: Build Mobile App with React Native
    {
      goal_id: goalIds[7],
      title: 'Setup React Native environment',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[7],
      title: 'Learn navigation patterns',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[7],
      title: 'Build app screens',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 300,
    },
    {
      goal_id: goalIds[7],
      title: 'Implement native features',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[7],
      title: 'Test on devices',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 120,
    },

    // Tasks for Goal 9: Learn System Design Patterns
    {
      goal_id: goalIds[8],
      title: 'Study scalability patterns',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[8],
      title: 'Learn load balancing',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[8],
      title: 'Study database sharding',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 150,
    },
    {
      goal_id: goalIds[8],
      title: 'Practice system design interviews',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 240,
    },

    // Tasks for Goal 10: Contribute to Open Source Project
    {
      goal_id: goalIds[9],
      title: 'Find suitable project',
      is_done: 1,
      energy_level: 'low',
      time_estimate: 60,
    },
    {
      goal_id: goalIds[9],
      title: 'Study codebase',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[9],
      title: 'Find good first issue',
      is_done: 0,
      energy_level: 'low',
      time_estimate: 30,
    },
    {
      goal_id: goalIds[9],
      title: 'Submit first PR',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 240,
    },

    // Additional tasks for remaining goals
    {
      goal_id: goalIds[10],
      title: 'Learn GraphQL basics',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[10],
      title: 'Study Apollo Client',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 150,
    },
    {
      goal_id: goalIds[10],
      title: 'Build GraphQL API',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 300,
    },

    {
      goal_id: goalIds[11],
      title: 'Setup GitHub Actions',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[11],
      title: 'Configure automated testing',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[11],
      title: 'Setup deployment automation',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 200,
    },

    {
      goal_id: goalIds[12],
      title: 'Install Docker',
      is_done: 1,
      energy_level: 'low',
      time_estimate: 30,
    },
    {
      goal_id: goalIds[12],
      title: 'Learn Docker basics',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[12],
      title: 'Study Kubernetes concepts',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 240,
    },
    {
      goal_id: goalIds[12],
      title: 'Deploy app to k8s cluster',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 300,
    },

    {
      goal_id: goalIds[13],
      title: 'Learn SQL optimization techniques',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 150,
    },
    {
      goal_id: goalIds[13],
      title: 'Practice query analysis',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[13],
      title: 'Implement database indexes',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 120,
    },

    {
      goal_id: goalIds[14],
      title: 'Setup WebSocket server',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[14],
      title: 'Build chat interface',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 240,
    },
    {
      goal_id: goalIds[14],
      title: 'Add message persistence',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[14],
      title: 'Implement user presence',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 90,
    },

    {
      goal_id: goalIds[15],
      title: 'Study utility types',
      is_done: 1,
      energy_level: 'low',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[15],
      title: 'Learn conditional types',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[15],
      title: 'Practice mapped types',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 150,
    },

    {
      goal_id: goalIds[16],
      title: 'Setup JWT authentication',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[16],
      title: 'Implement OAuth providers',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 240,
    },
    {
      goal_id: goalIds[16],
      title: 'Add role-based access control',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 150,
    },

    {
      goal_id: goalIds[17],
      title: 'Audit current performance',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 60,
    },
    {
      goal_id: goalIds[17],
      title: 'Optimize images and assets',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 120,
    },
    {
      goal_id: goalIds[17],
      title: 'Implement lazy loading',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 90,
    },
    {
      goal_id: goalIds[17],
      title: 'Add performance monitoring',
      is_done: 0,
      energy_level: 'low',
      time_estimate: 60,
    },

    {
      goal_id: goalIds[18],
      title: 'Design product catalog',
      is_done: 1,
      energy_level: 'medium',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[18],
      title: 'Build shopping cart',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 240,
    },
    {
      goal_id: goalIds[18],
      title: 'Integrate Stripe payments',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 200,
    },
    {
      goal_id: goalIds[18],
      title: 'Add order management',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 180,
    },

    {
      goal_id: goalIds[19],
      title: 'Setup Jest testing framework',
      is_done: 1,
      energy_level: 'low',
      time_estimate: 45,
    },
    {
      goal_id: goalIds[19],
      title: 'Write unit tests',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 200,
    },
    {
      goal_id: goalIds[19],
      title: 'Add integration tests',
      is_done: 0,
      energy_level: 'high',
      time_estimate: 180,
    },
    {
      goal_id: goalIds[19],
      title: 'Setup e2e testing with Playwright',
      is_done: 0,
      energy_level: 'medium',
      time_estimate: 150,
    },
  ]);

  // Insert 60 daily entries covering the past 2 months
  await db.insert(daily_entries).values([
    {
      date: '2025-06-14',
      energy: 'high',
      focus: 'high',
      main_goal: 'Complete AppliGO MVP',
      notes: 'Made great progress on UI and backend integration. Completed user authentication flow.',
      energy_level: 'high',
      mood: 'motivated',
    },
    {
      date: '2025-06-13',
      energy: 'medium',
      focus: 'medium',
      main_goal: 'Learn Drizzle ORM',
      notes: 'Read docs and tested migrations. Starting to feel comfortable with the syntax.',
      energy_level: 'medium',
      mood: 'focused',
    },
    {
      date: '2025-06-12',
      energy: 'high',
      focus: 'high',
      main_goal: 'Build Personal Portfolio Website',
      notes: 'Finished the landing page design. Really happy with the modern look.',
      energy_level: 'high',
      mood: 'creative',
    },
    {
      date: '2025-06-11',
      energy: 'low',
      focus: 'low',
      main_goal: 'Master React Server Components',
      notes: 'Had trouble concentrating today. Just did some light reading.',
      energy_level: 'low',
      mood: 'tired',
    },
    {
      date: '2025-06-10',
      energy: 'medium',
      focus: 'high',
      main_goal: 'Launch SaaS Side Project',
      notes: 'Defined MVP features and created project roadmap. Feeling organized.',
      energy_level: 'medium',
      mood: 'determined',
    },
    {
      date: '2025-06-09',
      energy: 'high',
      focus: 'medium',
      main_goal: 'Get AWS Solutions Architect Certification',
      notes: 'Studied compute services all morning. EC2 concepts are clicking now.',
      energy_level: 'high',
      mood: 'confident',
    },
    {
      date: '2025-06-08',
      energy: 'medium',
      focus: 'medium',
      main_goal: 'Improve Code Review Skills',
      notes: 'Read several articles on effective code reviews. Need to practice more.',
      energy_level: 'medium',
      mood: 'curious',
    },
    {
      date: '2025-06-07',
      energy: 'high',
      focus: 'high',
      main_goal: 'Build Mobile App with React Native',
      notes: 'Got the navigation working perfectly. App is starting to feel real!',
      energy_level: 'high',
      mood: 'excited',
    },
    {
      date: '2025-06-06',
      energy: 'low',
      focus: 'medium',
      main_goal: 'Learn System Design Patterns',
      notes: 'Slow day but managed to read about load balancing strategies.',
      energy_level: 'low',
      mood: 'steady',
    },
    {
      date: '2025-06-05',
      energy: 'medium',
      focus: 'high',
      main_goal: 'Contribute to Open Source Project',
      notes: 'Found a great project to contribute to. Spent time understanding the codebase.',
      energy_level: 'medium',
      mood: 'engaged',
    },
    {
      date: '2025-06-04',
      energy: 'high',
      focus: 'high',
      main_goal: 'Complete AppliGO MVP',
      notes: 'Productive day! Finished the database schema and started on API endpoints.',
      energy_level: 'high',
      mood: 'accomplished',
    },
    {
      date: '2025-06-03',
      energy: 'medium',
      focus: 'low',
      main_goal: 'Master GraphQL and Apollo',
      notes: 'Struggled with Apollo Client cache management. Need more practice.',
      energy_level: 'medium',
      mood: 'frustrated',
    },
    {
      date: '2025-06-02',
      energy: 'high',
      focus: 'medium',
      main_goal: 'Build CI/CD Pipeline',
      notes: "Set up GitHub Actions for the first time. It's more intuitive than expected.",
      energy_level: 'high',
      mood: 'satisfied',
    },
    {
      date: '2025-06-01',
      energy: 'medium',
      focus: 'high',
      main_goal: 'Learn Docker and Kubernetes',
      notes: 'Docker is making sense now. Kubernetes still feels overwhelming though.',
      energy_level: 'medium',
      mood: 'challenged',
    },
    {
      date: '2025-05-31',
      energy: 'low',
      focus: 'low',
      main_goal: 'Improve Database Performance',
      notes: 'Not my best day. Just reviewed some basic SQL optimization techniques.',
      energy_level: 'low',
      mood: 'sluggish',
    },
    {
      date: '2025-05-30',
      energy: 'high',
      focus: 'high',
      main_goal: 'Build Real-time Chat Application',
      notes: 'WebSocket server is working! Messages are flowing in real-time.',
      energy_level: 'high',
      mood: 'thrilled',
    },
    {
      date: '2025-05-29',
      energy: 'medium',
      focus: 'medium',
      main_goal: 'Learn TypeScript Advanced Features',
      notes: 'Utility types are powerful but complex. Made some good progress though.',
      energy_level: 'medium',
      mood: 'thoughtful',
    },
    {
      date: '2025-05-28',
      energy: 'high',
      focus: 'medium',
      main_goal: 'Implement Authentication System',
      notes: 'Started working on JWT implementation. Security is fascinating.',
      energy_level: 'high',
      mood: 'focused',
    },
    {
      date: '2025-05-27',
      energy: 'medium',
      focus: 'high',
      main_goal: 'Optimize Web Performance',
      notes: 'Ran performance audit and found several optimization opportunities.',
      energy_level: 'medium',
      mood: 'analytical',
    },
    {
      date: '2025-05-26',
      energy: 'low',
      focus: 'medium',
      main_goal: 'Build E-commerce Platform',
      notes: 'Slow progress on product catalog. Need to push through the complexity.',
      energy_level: 'low',
      mood: 'persevering',
    },
    {
      date: '2025-05-25',
      energy: 'high',
      focus: 'high',
      main_goal: 'Master Testing Strategies',
      notes: 'Set up Jest and wrote my first comprehensive test suite. Very satisfying!',
      energy_level: 'high',
      mood: 'accomplished',
    },
    {
      date: '2025-05-24',
      energy: 'medium',
      focus: 'low',
      main_goal: 'Complete AppliGO MVP',
      notes: 'Had meetings most of the day. Only got a little coding done.',
      energy_level: 'medium',
      mood: 'distracted',
    },
    {
      date: '2025-05-23',
      energy: 'high',
      focus: 'high',
      main_goal: 'Learn Drizzle ORM',
      notes: 'Built a sample project with Drizzle. The type safety is amazing!',
      energy_level: 'high',
      mood: 'impressed',
    },
    {
      date: '2025-05-22',
      energy: 'medium',
      focus: 'medium',
      main_goal: 'Build Personal Portfolio Website',
      notes: 'Worked on the projects showcase section. Need better project descriptions.',
      energy_level: 'medium',
      mood: 'creative',
    },
    {
      date: '2025-05-21',
      energy: 'low',
      focus: 'high',
      main_goal: 'Master React Server Components',
      notes: 'Low energy but good focus. Made progress on data fetching patterns.',
      energy_level: 'low',
      mood: 'concentrated',
    },
    {
      date: '2025-05-20',
      energy: 'high',
      focus: 'medium',
      main_goal: 'Launch SaaS Side Project',
      notes: 'Did market research and competitor analysis. Market looks promising!',
      energy_level: 'high',
      mood: 'optimistic',
    },
    {
      date: '2025-05-19',
      energy: 'medium',
      focus: 'high',
      main_goal: 'Get AWS Solutions Architect Certification',
      notes: 'Deep dive into storage services. S3 has so many features!',
      energy_level: 'medium',
      mood: 'studious',
    },
  ]);
}
